// <auto-generated />
using System;
using JasperGreen18.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JasperGreen18.Migrations
{
    [DbContext(typeof(JasperGreenContext))]
    [Migration("20201202152831_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("JasperGreen18.Models.Crew", b =>
                {
                    b.Property<int>("CrewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrewForemanID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrewMember1ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrewMember2ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CrewID");

                    b.HasIndex("CrewForemanID");

                    b.HasIndex("CrewMember1ID");

                    b.HasIndex("CrewMember2ID");

                    b.ToTable("Crews");

                    b.HasData(
                        new
                        {
                            CrewID = 1,
                            CrewForemanID = 1,
                            CrewMember1ID = 2,
                            CrewMember2ID = 3
                        },
                        new
                        {
                            CrewID = 2,
                            CrewForemanID = 4,
                            CrewMember1ID = 5,
                            CrewMember2ID = 6
                        },
                        new
                        {
                            CrewID = 3,
                            CrewForemanID = 7,
                            CrewMember1ID = 8,
                            CrewMember2ID = 9
                        },
                        new
                        {
                            CrewID = 4,
                            CrewForemanID = 10,
                            CrewMember1ID = 11,
                            CrewMember2ID = 12
                        },
                        new
                        {
                            CrewID = 5,
                            CrewForemanID = 13,
                            CrewMember1ID = 14,
                            CrewMember2ID = 15
                        });
                });

            modelBuilder.Entity("JasperGreen18.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingZip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            BillingAddress = "6432 Elm Crest Ct",
                            BillingCity = "College Station",
                            BillingState = "TX",
                            BillingZip = "77840",
                            CustomerFirstName = "Susan",
                            CustomerLastName = "Anthony",
                            CustomerPhone = "8173083025"
                        },
                        new
                        {
                            CustomerID = 2,
                            BillingAddress = "2099 Alibi Rd",
                            BillingCity = "Bryan",
                            BillingState = "TX",
                            BillingZip = "77842",
                            CustomerFirstName = "Sarah",
                            CustomerLastName = "Timmins",
                            CustomerPhone = "9991029412"
                        },
                        new
                        {
                            CustomerID = 3,
                            BillingAddress = "87 Cool Plaza Rd",
                            BillingCity = "College Station",
                            BillingState = "TX",
                            BillingZip = "77844",
                            CustomerFirstName = "Mike",
                            CustomerLastName = "Scott",
                            CustomerPhone = "7281048294"
                        },
                        new
                        {
                            CustomerID = 4,
                            BillingAddress = "8243 Celtics Ave",
                            BillingCity = "Bryan",
                            BillingState = "TX",
                            BillingZip = "77816",
                            CustomerFirstName = "Larry",
                            CustomerLastName = "Bird",
                            CustomerPhone = "5927731088"
                        },
                        new
                        {
                            CustomerID = 5,
                            BillingAddress = "6172 Texas Ave S",
                            BillingCity = "College Station",
                            BillingState = "TX",
                            BillingZip = "77840",
                            CustomerFirstName = "Tim",
                            CustomerLastName = "Morgan",
                            CustomerPhone = "8229136239"
                        });
                });

            modelBuilder.Entity("JasperGreen18.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrewForemanID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrewMember1ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrewMember2ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Josh",
                            EmployeeLastName = "Tipton",
                            HireDate = new DateTime(2020, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 9.31m,
                            JobTitle = "Foreman",
                            SSN = "827937161"
                        },
                        new
                        {
                            EmployeeID = 2,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "James",
                            EmployeeLastName = "Smith",
                            HireDate = new DateTime(2020, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 10.11m,
                            JobTitle = "Foreman",
                            SSN = "819267345"
                        },
                        new
                        {
                            EmployeeID = 3,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Adam",
                            EmployeeLastName = "Stevens",
                            HireDate = new DateTime(2020, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 10.00m,
                            JobTitle = "Basic Crew Member",
                            SSN = "191675544"
                        },
                        new
                        {
                            EmployeeID = 4,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Peter",
                            EmployeeLastName = "Parker",
                            HireDate = new DateTime(2020, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 10.00m,
                            JobTitle = "Basic Crew Member",
                            SSN = "907665312"
                        },
                        new
                        {
                            EmployeeID = 5,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Tony",
                            EmployeeLastName = "Stark",
                            HireDate = new DateTime(2020, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 11.15m,
                            JobTitle = "Basic Crew Member",
                            SSN = "767889421"
                        },
                        new
                        {
                            EmployeeID = 6,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Clint",
                            EmployeeLastName = "Barton",
                            HireDate = new DateTime(2020, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 10.50m,
                            JobTitle = "Foreman",
                            SSN = "112772445"
                        },
                        new
                        {
                            EmployeeID = 7,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Chadwick",
                            EmployeeLastName = "Boseman",
                            HireDate = new DateTime(2020, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 11.23m,
                            JobTitle = "Foreman",
                            SSN = "322567256"
                        },
                        new
                        {
                            EmployeeID = 8,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Jonah",
                            EmployeeLastName = "Hill",
                            HireDate = new DateTime(2020, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 10.00m,
                            JobTitle = "Foreman",
                            SSN = "829182197"
                        },
                        new
                        {
                            EmployeeID = 9,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Juan",
                            EmployeeLastName = "Rodriguez",
                            HireDate = new DateTime(2020, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 10.43m,
                            JobTitle = "Foreman",
                            SSN = "881904418"
                        },
                        new
                        {
                            EmployeeID = 10,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Alex",
                            EmployeeLastName = "Escobar",
                            HireDate = new DateTime(2020, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 12.19m,
                            JobTitle = "Foreman",
                            SSN = "221339153"
                        },
                        new
                        {
                            EmployeeID = 11,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Tanner",
                            EmployeeLastName = "Ray",
                            HireDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 12.31m,
                            JobTitle = "Foreman",
                            SSN = "705628112"
                        },
                        new
                        {
                            EmployeeID = 12,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Michael",
                            EmployeeLastName = "Jackson",
                            HireDate = new DateTime(2020, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 11.46m,
                            JobTitle = "Foreman",
                            SSN = "808976663"
                        },
                        new
                        {
                            EmployeeID = 13,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Stephen",
                            EmployeeLastName = "Hamster",
                            HireDate = new DateTime(2020, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 9.49m,
                            JobTitle = "Foreman",
                            SSN = "623112013"
                        },
                        new
                        {
                            EmployeeID = 14,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Jack",
                            EmployeeLastName = "Reacher",
                            HireDate = new DateTime(2020, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 10.05m,
                            JobTitle = "Foreman",
                            SSN = "516620901"
                        },
                        new
                        {
                            EmployeeID = 15,
                            CrewForemanID = 0,
                            CrewMember1ID = 0,
                            CrewMember2ID = 0,
                            EmployeeFirstName = "Bruce",
                            EmployeeLastName = "Banner",
                            HireDate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HourlyRate = 11.07m,
                            JobTitle = "Foreman",
                            SSN = "716809112"
                        });
                });

            modelBuilder.Entity("JasperGreen18.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentID = 1,
                            CustomerID = 2,
                            PaymentAmount = 200m,
                            PaymentDate = new DateTime(2020, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentID = 2,
                            CustomerID = 1,
                            PaymentAmount = 225m,
                            PaymentDate = new DateTime(2020, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentID = 3,
                            CustomerID = 5,
                            PaymentAmount = 150m,
                            PaymentDate = new DateTime(2020, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentID = 4,
                            CustomerID = 2,
                            PaymentAmount = 325m,
                            PaymentDate = new DateTime(2020, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentID = 5,
                            CustomerID = 1,
                            PaymentAmount = 170m,
                            PaymentDate = new DateTime(2020, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentID = 6,
                            CustomerID = 3,
                            PaymentAmount = 125m,
                            PaymentDate = new DateTime(2020, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentID = 7,
                            CustomerID = 3,
                            PaymentAmount = 190m,
                            PaymentDate = new DateTime(2020, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentID = 8,
                            CustomerID = 5,
                            PaymentAmount = 165m,
                            PaymentDate = new DateTime(2020, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentID = 9,
                            CustomerID = 4,
                            PaymentAmount = 225m,
                            PaymentDate = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentID = 10,
                            CustomerID = 2,
                            PaymentAmount = 300m,
                            PaymentDate = new DateTime(2020, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PaymentID = 11,
                            CustomerID = 3,
                            PaymentAmount = 150m,
                            PaymentDate = new DateTime(2020, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("JasperGreen18.Models.Property", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyZip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("TEXT");

                    b.HasKey("PropertyID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyID = 1,
                            CustomerID = 3,
                            PropertyAddress = "4433 Elm  Ave",
                            PropertyCity = "College Station",
                            PropertyState = "TX",
                            PropertyZip = "77840",
                            ServiceFee = 210.99m
                        },
                        new
                        {
                            PropertyID = 2,
                            CustomerID = 1,
                            PropertyAddress = "9431 Brandon St",
                            PropertyCity = "College Station",
                            PropertyState = "TX",
                            PropertyZip = "77839",
                            ServiceFee = 99.99m
                        },
                        new
                        {
                            PropertyID = 3,
                            CustomerID = 5,
                            PropertyAddress = "216 Vanessa Ln",
                            PropertyCity = "College Station",
                            PropertyState = "TX",
                            PropertyZip = "77840",
                            ServiceFee = 49.99m
                        },
                        new
                        {
                            PropertyID = 4,
                            CustomerID = 2,
                            PropertyAddress = "2113 Mesquite Rd",
                            PropertyCity = "College Station",
                            PropertyState = "TX",
                            PropertyZip = "77840",
                            ServiceFee = 69.99m
                        },
                        new
                        {
                            PropertyID = 5,
                            CustomerID = 4,
                            PropertyAddress = "8121 South Beach Ct",
                            PropertyCity = "College Station",
                            PropertyState = "TX",
                            PropertyZip = "77840",
                            ServiceFee = 125.00m
                        },
                        new
                        {
                            PropertyID = 6,
                            CustomerID = 4,
                            PropertyAddress = "2111 Oho Ln",
                            PropertyCity = "College Station",
                            PropertyState = "TX",
                            PropertyZip = "77840",
                            ServiceFee = 125.00m
                        });
                });

            modelBuilder.Entity("JasperGreen18.Models.ProvideService", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrewID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceID");

                    b.HasIndex("CrewID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("PropertyID");

                    b.ToTable("ProvideServices");

                    b.HasData(
                        new
                        {
                            ServiceID = 1,
                            CrewID = 1,
                            CustomerID = 1,
                            PaymentID = 1,
                            PropertyID = 1,
                            ServiceDate = new DateTime(2020, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceFee = 80m
                        },
                        new
                        {
                            ServiceID = 2,
                            CrewID = 3,
                            CustomerID = 2,
                            PaymentID = 2,
                            PropertyID = 2,
                            ServiceDate = new DateTime(2020, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceFee = 60m
                        },
                        new
                        {
                            ServiceID = 3,
                            CrewID = 4,
                            CustomerID = 1,
                            PaymentID = 3,
                            PropertyID = 3,
                            ServiceDate = new DateTime(2020, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceFee = 120m
                        },
                        new
                        {
                            ServiceID = 4,
                            CrewID = 1,
                            CustomerID = 1,
                            PaymentID = 4,
                            PropertyID = 5,
                            ServiceDate = new DateTime(2020, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceFee = 100m
                        },
                        new
                        {
                            ServiceID = 5,
                            CrewID = 3,
                            CustomerID = 4,
                            PaymentID = 5,
                            PropertyID = 2,
                            ServiceDate = new DateTime(2020, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceFee = 200m
                        },
                        new
                        {
                            ServiceID = 6,
                            CrewID = 3,
                            CustomerID = 3,
                            PaymentID = 6,
                            PropertyID = 3,
                            ServiceDate = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceFee = 250m
                        },
                        new
                        {
                            ServiceID = 7,
                            CrewID = 3,
                            CustomerID = 5,
                            PaymentID = 7,
                            PropertyID = 2,
                            ServiceDate = new DateTime(2020, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceFee = 29.99m
                        },
                        new
                        {
                            ServiceID = 8,
                            CrewID = 1,
                            CustomerID = 5,
                            PaymentID = 8,
                            PropertyID = 2,
                            ServiceDate = new DateTime(2020, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceFee = 225m
                        },
                        new
                        {
                            ServiceID = 9,
                            CrewID = 1,
                            CustomerID = 2,
                            PaymentID = 9,
                            PropertyID = 2,
                            ServiceDate = new DateTime(2020, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceFee = 325m
                        },
                        new
                        {
                            ServiceID = 10,
                            CrewID = 4,
                            CustomerID = 4,
                            PaymentID = 10,
                            PropertyID = 4,
                            ServiceDate = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceFee = 175m
                        });
                });

            modelBuilder.Entity("JasperGreen18.Models.State", b =>
                {
                    b.Property<string>("StateID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StateID");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateID = "AL",
                            Name = "Alabama"
                        },
                        new
                        {
                            StateID = "AK",
                            Name = "Alaska"
                        },
                        new
                        {
                            StateID = "AZ",
                            Name = "Arizona"
                        },
                        new
                        {
                            StateID = "AR",
                            Name = "Arkansas"
                        },
                        new
                        {
                            StateID = "CA",
                            Name = "California"
                        },
                        new
                        {
                            StateID = "CO",
                            Name = "Colorado"
                        },
                        new
                        {
                            StateID = "CT",
                            Name = "Connecticut"
                        },
                        new
                        {
                            StateID = "DE",
                            Name = "Delaware"
                        },
                        new
                        {
                            StateID = "DC",
                            Name = "District Of Columbia"
                        },
                        new
                        {
                            StateID = "FL",
                            Name = "Florida"
                        },
                        new
                        {
                            StateID = "GA",
                            Name = "Georgia"
                        },
                        new
                        {
                            StateID = "HI",
                            Name = "Hawaii"
                        },
                        new
                        {
                            StateID = "ID",
                            Name = "Idaho"
                        },
                        new
                        {
                            StateID = "IL",
                            Name = "Illinois"
                        },
                        new
                        {
                            StateID = "IN",
                            Name = "Indiana"
                        },
                        new
                        {
                            StateID = "IA",
                            Name = "Iowa"
                        },
                        new
                        {
                            StateID = "KS",
                            Name = "Kansas"
                        },
                        new
                        {
                            StateID = "KY",
                            Name = "Kentucky"
                        },
                        new
                        {
                            StateID = "LA",
                            Name = "Louisiana"
                        },
                        new
                        {
                            StateID = "ME",
                            Name = "Maine"
                        },
                        new
                        {
                            StateID = "MD",
                            Name = "Maryland"
                        },
                        new
                        {
                            StateID = "MA",
                            Name = "Massachusetts"
                        },
                        new
                        {
                            StateID = "MI",
                            Name = "Michigan"
                        },
                        new
                        {
                            StateID = "MN",
                            Name = "Minnesota"
                        },
                        new
                        {
                            StateID = "MS",
                            Name = "Mississippi"
                        },
                        new
                        {
                            StateID = "MO",
                            Name = "Missouri"
                        },
                        new
                        {
                            StateID = "MT",
                            Name = "Montana"
                        },
                        new
                        {
                            StateID = "NE",
                            Name = "Nebraska"
                        },
                        new
                        {
                            StateID = "NV",
                            Name = "Nevada"
                        },
                        new
                        {
                            StateID = "NH",
                            Name = "New Hampshire"
                        },
                        new
                        {
                            StateID = "NJ",
                            Name = "New Jersey"
                        },
                        new
                        {
                            StateID = "NM",
                            Name = "New Mexico"
                        },
                        new
                        {
                            StateID = "NY",
                            Name = "New York"
                        },
                        new
                        {
                            StateID = "NC",
                            Name = "North Carolina"
                        },
                        new
                        {
                            StateID = "ND",
                            Name = "North Dakota"
                        },
                        new
                        {
                            StateID = "OH",
                            Name = "Ohio"
                        },
                        new
                        {
                            StateID = "OK",
                            Name = "Oklahoma"
                        },
                        new
                        {
                            StateID = "OR",
                            Name = "Oregon"
                        },
                        new
                        {
                            StateID = "PA",
                            Name = "Pennsylvania"
                        },
                        new
                        {
                            StateID = "RI",
                            Name = "Rhode Island"
                        },
                        new
                        {
                            StateID = "SC",
                            Name = "South Carolina"
                        },
                        new
                        {
                            StateID = "SD",
                            Name = "South Dakota"
                        },
                        new
                        {
                            StateID = "TN",
                            Name = "Tennessee"
                        },
                        new
                        {
                            StateID = "TX",
                            Name = "Texas"
                        },
                        new
                        {
                            StateID = "UT",
                            Name = "Utah"
                        },
                        new
                        {
                            StateID = "VT",
                            Name = "Vermont"
                        },
                        new
                        {
                            StateID = "VA",
                            Name = "Virginia"
                        },
                        new
                        {
                            StateID = "WA",
                            Name = "Washington"
                        },
                        new
                        {
                            StateID = "WV",
                            Name = "West Virginia"
                        },
                        new
                        {
                            StateID = "WI",
                            Name = "Wisconsin"
                        },
                        new
                        {
                            StateID = "WY",
                            Name = "Wyoming"
                        });
                });

            modelBuilder.Entity("JasperGreen18.Models.Crew", b =>
                {
                    b.HasOne("JasperGreen18.Models.Employee", "CrewForeman")
                        .WithMany("CrewsF")
                        .HasForeignKey("CrewForemanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JasperGreen18.Models.Employee", "CrewMember1")
                        .WithMany("Crews1")
                        .HasForeignKey("CrewMember1ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JasperGreen18.Models.Employee", "CrewMember2")
                        .WithMany("Crews2")
                        .HasForeignKey("CrewMember2ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewForeman");

                    b.Navigation("CrewMember1");

                    b.Navigation("CrewMember2");
                });

            modelBuilder.Entity("JasperGreen18.Models.Payment", b =>
                {
                    b.HasOne("JasperGreen18.Models.Customer", "CurrentCustomer")
                        .WithMany("CustomerPayments")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentCustomer");
                });

            modelBuilder.Entity("JasperGreen18.Models.Property", b =>
                {
                    b.HasOne("JasperGreen18.Models.Customer", "PropertyOwner")
                        .WithMany("CustomerProperties")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyOwner");
                });

            modelBuilder.Entity("JasperGreen18.Models.ProvideService", b =>
                {
                    b.HasOne("JasperGreen18.Models.Crew", "CurrentCrew")
                        .WithMany()
                        .HasForeignKey("CrewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JasperGreen18.Models.Customer", "CurrentCustomer")
                        .WithMany("CustomerServices")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JasperGreen18.Models.Payment", "CurrentPayment")
                        .WithMany("PaymentServices")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JasperGreen18.Models.Property", "CurrentProperty")
                        .WithMany("PropertyServices")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentCrew");

                    b.Navigation("CurrentCustomer");

                    b.Navigation("CurrentPayment");

                    b.Navigation("CurrentProperty");
                });

            modelBuilder.Entity("JasperGreen18.Models.Customer", b =>
                {
                    b.Navigation("CustomerPayments");

                    b.Navigation("CustomerProperties");

                    b.Navigation("CustomerServices");
                });

            modelBuilder.Entity("JasperGreen18.Models.Employee", b =>
                {
                    b.Navigation("Crews1");

                    b.Navigation("Crews2");

                    b.Navigation("CrewsF");
                });

            modelBuilder.Entity("JasperGreen18.Models.Payment", b =>
                {
                    b.Navigation("PaymentServices");
                });

            modelBuilder.Entity("JasperGreen18.Models.Property", b =>
                {
                    b.Navigation("PropertyServices");
                });
#pragma warning restore 612, 618
        }
    }
}
